# Site settings
title: ""
author: "Sando George"
description: ""
keywords: ""
biography: ""
colophon: "© 2017 by Sando George.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a> (theme by <a>http://hugosereno.eu/</a>)."

baseurl: ""
url: "http://sandogeorge.github.io"

twitter_username: sandogee
github_username: sandogeorge
linkedin_username: sandogeorge
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
