# Site settings
title: "Life, Computing and Mathematics"
author: "Sando George"
description: "A blog to document my thoughts on issues related to my research interests and life in general."
keywords: "Life, Computing, Mathematics, Mobile Computing, Multiagent Systems, Topological Data Analysis"
biography: "I am an aspiring computer scientist with interests in multiagent systems, mobile computing, cloud applications architecture, embedded linux systems, topological data analysis and catastrophe theory."
colophon: "by Sando George.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a> (adapted from Papyrus theme by <a href='http://hugosereno.eu/'>Hugo Sereno Ferreira</a>)."

baseurl: ""
url: "http://sandogeorge.github.io"

twitter_username: sandogee
github_username: sandogeorge
linkedin_username: sandogeorge
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
